// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/fredyzh/ecom/product/app/config/v1"
	v1_3 "github.com/fredyzh/ecom/product/app/internal/server/v1"
	v1_2 "github.com/fredyzh/ecom/product/app/internal/service/v1"
)

// Injectors from wire.go:

func initApp(server_GRPC *v1.Server_GRPC, server_HTTP *v1.Server_HTTP, data_Database *v1.Data_Database, productService *v1_2.ProductService) (*App, error) {
	serveMux := v1_3.NewHTTPServer(server_HTTP, productService)
	server := v1_3.NewGRPCServer(server_GRPC, productService)
	productBusiness := v1_3.NewDBInterface(data_Database, productService)
	app := newApp(serveMux, server, server_GRPC, server_HTTP, productBusiness)
	return app, nil
}
